### ISSUE TITLE
Basis_test failed.

### ISSUE THREAD

**Issue by tmhuysen** [lelemmen/libwrp#29]
Only the Basis_test failed.
>Test project /usr/local/libwrp/build
    Start 1: Basis_test
1/4 Test #1: Basis_test .......................***Failed    0.01 sec
    Start 2: Molecule_test
2/4 Test #2: Molecule_test ....................   Passed    0.01 sec
    Start 3: geometry_test
3/4 Test #3: geometry_test ....................   Passed    0.01 sec
    Start 4: transformations_test
4/4 Test #4: transformations_test .............   Passed    0.02 sec

After further investigation the result of the error is: 

>unknown location:0: fatal error: in "constructor": std::runtime_error: BasisSet::data_path(): path "NONE/share/libint/2.3.1/basis" is not valid

For each of the tests in the Basis_test.
(Note that to find this error I downloaded it separately and opened it in Clion this could accompany other issues.)

**Comment by lelemmen** [comment]
This is a problem with the libint installation. As can be read in the `.travis.yml`-file, 

>   # Finally, since libint often complains about reading the basis sets, specify a LIBINT_DATA_PATH to help libint find the files.
>   - export LIBINT_DATA_PATH=/usr/local/libint/2.3.1/share/libint/2.3.1/basis

Add the last line to your bash profile and you should be good to go. I will document this problem in the wiki.

**Comment by tmhuysen** [comment]
I had already executed that command however I did not do it in the my Users/MyUser directory. 
I also did 
"echo 'export LIBINT_DATA_PATH=/usr/local/libint/2.3.1/share/libint/2.3.1/basis' >>~/.bash_profile"
I do not know which one fixed the problem. But it is fixed now.
